version: '3.8'

services:
  app:
    build: .
    container_name: server_monitor_container
    restart: always
    ports:
      - "4000:3000"
      - "4001:3002"
      - "4040:8082"
    
    # Yahan humne Volume (USB) lagaya hai ðŸ‘‡
    volumes:
      - ./server_health.log:/app/server_health.log
